"""add roll_number and email to students

Revision ID: d19e949625c8
Revises: f90885b8f385
Create Date: 2025-12-22 00:41:27.652263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19e949625c8'
down_revision: Union[str, Sequence[str], None] = 'f90885b8f385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('roll_number', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'students', ['email'])
    op.create_unique_constraint(None, 'students', ['roll_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'email')
    op.drop_column('students', 'roll_number')
    # ### end Alembic commands ###
